// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnhMOraEbCSkydd7C9igwM1gUKEwFqazU',
    appId: '1:253056153381:web:a433a1c28664a2195b0ccc',
    messagingSenderId: '253056153381',
    projectId: 'souk-1baf1',
    authDomain: 'souk-1baf1.firebaseapp.com',
    databaseURL: 'https://souk-1baf1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'souk-1baf1.appspot.com',
    measurementId: 'G-HCYJ8VH45W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHdKIsCdXH4SZYtRFEJxJ-0sglv6i7Cww',
    appId: '1:253056153381:android:a41355d4cec9340b5b0ccc',
    messagingSenderId: '253056153381',
    projectId: 'souk-1baf1',
    databaseURL: 'https://souk-1baf1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'souk-1baf1.appspot.com',
  );
}
